/**
 * AUTO-GENERATED EVENT TYPES
 * Do not edit this file manually. Run scripts/generate-event-types.ts instead.
 */

import { Step } from "../gen/exa/gemini_coder/proto/trajectory_pb.js";

/**
 * Helper that derives the Value type from a Step case at the type level.
 */
type StepValue<T extends string> = Extract<NonNullable<Step["step"]>, { case: T }>["value"];

/**
 * All event constants available on Cascade.
 */
export const CascadeEvents = {
    // Basic Events
    Text: "text" as const,
    Thinking: "thinking" as const,
    Interaction: "interaction" as const,
    CommandOutput: "commandOutput" as const,
    StepNew: "stepNew" as const,
    StepUpdate: "stepUpdate" as const,
    StatusChange: "statusChange" as const,
    Error: "error" as const,
    Done: "done" as const,
    RawUpdate: "rawUpdate" as const,
    All: "all" as const,
    Other: "other" as const,

    // Auto-generated Step-specific Events
    AgencyToolCall: "step:agencyToolCall" as const,
    AskQuestion: "step:askQuestion" as const,
    BlazeBuildTargets: "step:blazeBuildTargets" as const,
    BlazeTestTargets: "step:blazeTestTargets" as const,
    BrainUpdate: "step:brainUpdate" as const,
    BrowserClickElement: "step:browserClickElement" as const,
    BrowserDragPixelToPixel: "step:browserDragPixelToPixel" as const,
    BrowserGetDom: "step:browserGetDom" as const,
    BrowserGetNetworkRequest: "step:browserGetNetworkRequest" as const,
    BrowserInput: "step:browserInput" as const,
    BrowserListNetworkRequests: "step:browserListNetworkRequests" as const,
    BrowserMouseDown: "step:browserMouseDown" as const,
    BrowserMouseUp: "step:browserMouseUp" as const,
    BrowserMouseWheel: "step:browserMouseWheel" as const,
    BrowserMoveMouse: "step:browserMoveMouse" as const,
    BrowserPressKey: "step:browserPressKey" as const,
    BrowserRefreshPage: "step:browserRefreshPage" as const,
    BrowserResizeWindow: "step:browserResizeWindow" as const,
    BrowserScroll: "step:browserScroll" as const,
    BrowserScrollDown: "step:browserScrollDown" as const,
    BrowserScrollUp: "step:browserScrollUp" as const,
    BrowserSelectOption: "step:browserSelectOption" as const,
    BrowserSubagent: "step:browserSubagent" as const,
    BuildCleaner: "step:buildCleaner" as const,
    CaptureBrowserConsoleLogs: "step:captureBrowserConsoleLogs" as const,
    CaptureBrowserScreenshot: "step:captureBrowserScreenshot" as const,
    CheckDeployStatus: "step:checkDeployStatus" as const,
    Checkpoint: "step:checkpoint" as const,
    ClickBrowserPixel: "step:clickBrowserPixel" as const,
    Clipboard: "step:clipboard" as const,
    CloudsqlExecuteSql: "step:cloudsqlExecuteSql" as const,
    CloudsqlUpdateSchema: "step:cloudsqlUpdateSchema" as const,
    CodeAcknowledgement: "step:codeAcknowledgement" as const,
    CodeAction: "step:codeAction" as const,
    CodeSearch: "step:codeSearch" as const,
    CommandStatus: "step:commandStatus" as const,
    Compile: "step:compile" as const,
    CompileApplet: "step:compileApplet" as const,
    ConversationHistory: "step:conversationHistory" as const,
    Critique: "step:critique" as const,
    DeleteDirectory: "step:deleteDirectory" as const,
    DeployFirebase: "step:deployFirebase" as const,
    Dummy: "step:dummy" as const,
    EditNotebook: "step:editNotebook" as const,
    EphemeralMessage: "step:ephemeralMessage" as const,
    ErrorMessage: "step:errorMessage" as const,
    ExecuteBrowserJavascript: "step:executeBrowserJavascript" as const,
    ExecuteNotebook: "step:executeNotebook" as const,
    FileBreakdown: "step:fileBreakdown" as const,
    FileChange: "step:fileChange" as const,
    Find: "step:find" as const,
    FindAllReferences: "step:findAllReferences" as const,
    Findings: "step:findings" as const,
    Finish: "step:finish" as const,
    GenerateImage: "step:generateImage" as const,
    Generic: "step:generic" as const,
    GitCommit: "step:gitCommit" as const,
    GrepSearch: "step:grepSearch" as const,
    InstallAppletDependencies: "step:installAppletDependencies" as const,
    InstallAppletPackage: "step:installAppletPackage" as const,
    InternalSearch: "step:internalSearch" as const,
    InvokeSubagent: "step:invokeSubagent" as const,
    KiInsertion: "step:kiInsertion" as const,
    KnowledgeArtifacts: "step:knowledgeArtifacts" as const,
    KnowledgeGeneration: "step:knowledgeGeneration" as const,
    LintApplet: "step:lintApplet" as const,
    LintDiff: "step:lintDiff" as const,
    ListBrowserPages: "step:listBrowserPages" as const,
    ListDirectory: "step:listDirectory" as const,
    ListResources: "step:listResources" as const,
    LookupKnowledgeBase: "step:lookupKnowledgeBase" as const,
    ManagerFeedback: "step:managerFeedback" as const,
    McpTool: "step:mcpTool" as const,
    Memory: "step:memory" as const,
    Moma: "step:moma" as const,
    Move: "step:move" as const,
    Mquery: "step:mquery" as const,
    NotifyUser: "step:notifyUser" as const,
    OpenBrowserUrl: "step:openBrowserUrl" as const,
    PlanInput: "step:planInput" as const,
    PlannerResponse: "step:plannerResponse" as const,
    PostPrReview: "step:postPrReview" as const,
    ProposalFeedback: "step:proposalFeedback" as const,
    ProposeCode: "step:proposeCode" as const,
    ReadBrowserPage: "step:readBrowserPage" as const,
    ReadNotebook: "step:readNotebook" as const,
    ReadResource: "step:readResource" as const,
    ReadTerminal: "step:readTerminal" as const,
    ReadUrlContent: "step:readUrlContent" as const,
    RestartDevServer: "step:restartDevServer" as const,
    RetrieveContent: "step:retrieveContent" as const,
    RetrieveMemory: "step:retrieveMemory" as const,
    RpcAction: "step:rpcAction" as const,
    RunCommand: "step:runCommand" as const,
    RunExtensionCode: "step:runExtensionCode" as const,
    SearchKnowledgeBase: "step:searchKnowledgeBase" as const,
    SearchWeb: "step:searchWeb" as const,
    SendCommandInput: "step:sendCommandInput" as const,
    SetUpCloudsql: "step:setUpCloudsql" as const,
    SetUpFirebase: "step:setUpFirebase" as const,
    ShellExec: "step:shellExec" as const,
    SuggestedResponses: "step:suggestedResponses" as const,
    SystemMessage: "step:systemMessage" as const,
    TaskBoundary: "step:taskBoundary" as const,
    ToolCallChoice: "step:toolCallChoice" as const,
    ToolCallProposal: "step:toolCallProposal" as const,
    TrajectoryChoice: "step:trajectoryChoice" as const,
    TrajectorySearch: "step:trajectorySearch" as const,
    UserInput: "step:userInput" as const,
    ViewCodeItem: "step:viewCodeItem" as const,
    ViewContentChunk: "step:viewContentChunk" as const,
    ViewFile: "step:viewFile" as const,
    ViewFileOutline: "step:viewFileOutline" as const,
    Wait: "step:wait" as const,
    WorkspaceApi: "step:workspaceApi" as const,
    WriteBlob: "step:writeBlob" as const,
    WriteToFile: "step:writeToFile" as const,
} as const;

/**
 * Event name -> payload type mapping
 */
export interface CascadeEventPayloads {
    "text": { delta: string; fullText: string; stepIndex: number };
    "thinking": { delta: string; fullText: string; stepIndex: number };
    "interaction": import("./index.js").ApprovalRequest;
    "commandOutput": { delta: string; fullText: string; stream: "stdout" | "stderr"; stepIndex: number };
    "stepNew": { step: import("./index.js").CascadeStep };
    "stepUpdate": { step: import("./index.js").CascadeStep; previousStatus: import("./index.js").StepStatus };
    "statusChange": { status: import("./index.js").RunStatus; previousStatus: import("./index.js").RunStatus };
    "error": any;
    "done": {};
    "rawUpdate": import("../gen/exa/jetski_cortex_pb/jetski_cortex_pb.js").CascadeState;
    "all": { event: string; data: any };
    "other": import("./index.js").CascadeStep;

    // Auto-generated Step Payload Mappings
    "step:agencyToolCall": import("./index.js").CascadeStep & { type: "agencyToolCall", value: StepValue<"agencyToolCall"> };
    "step:askQuestion": import("./index.js").CascadeStep & { type: "askQuestion", value: StepValue<"askQuestion"> };
    "step:blazeBuildTargets": import("./index.js").CascadeStep & { type: "blazeBuildTargets", value: StepValue<"blazeBuildTargets"> };
    "step:blazeTestTargets": import("./index.js").CascadeStep & { type: "blazeTestTargets", value: StepValue<"blazeTestTargets"> };
    "step:brainUpdate": import("./index.js").CascadeStep & { type: "brainUpdate", value: StepValue<"brainUpdate"> };
    "step:browserClickElement": import("./index.js").CascadeStep & { type: "browserClickElement", value: StepValue<"browserClickElement"> };
    "step:browserDragPixelToPixel": import("./index.js").CascadeStep & { type: "browserDragPixelToPixel", value: StepValue<"browserDragPixelToPixel"> };
    "step:browserGetDom": import("./index.js").CascadeStep & { type: "browserGetDom", value: StepValue<"browserGetDom"> };
    "step:browserGetNetworkRequest": import("./index.js").CascadeStep & { type: "browserGetNetworkRequest", value: StepValue<"browserGetNetworkRequest"> };
    "step:browserInput": import("./index.js").CascadeStep & { type: "browserInput", value: StepValue<"browserInput"> };
    "step:browserListNetworkRequests": import("./index.js").CascadeStep & { type: "browserListNetworkRequests", value: StepValue<"browserListNetworkRequests"> };
    "step:browserMouseDown": import("./index.js").CascadeStep & { type: "browserMouseDown", value: StepValue<"browserMouseDown"> };
    "step:browserMouseUp": import("./index.js").CascadeStep & { type: "browserMouseUp", value: StepValue<"browserMouseUp"> };
    "step:browserMouseWheel": import("./index.js").CascadeStep & { type: "browserMouseWheel", value: StepValue<"browserMouseWheel"> };
    "step:browserMoveMouse": import("./index.js").CascadeStep & { type: "browserMoveMouse", value: StepValue<"browserMoveMouse"> };
    "step:browserPressKey": import("./index.js").CascadeStep & { type: "browserPressKey", value: StepValue<"browserPressKey"> };
    "step:browserRefreshPage": import("./index.js").CascadeStep & { type: "browserRefreshPage", value: StepValue<"browserRefreshPage"> };
    "step:browserResizeWindow": import("./index.js").CascadeStep & { type: "browserResizeWindow", value: StepValue<"browserResizeWindow"> };
    "step:browserScroll": import("./index.js").CascadeStep & { type: "browserScroll", value: StepValue<"browserScroll"> };
    "step:browserScrollDown": import("./index.js").CascadeStep & { type: "browserScrollDown", value: StepValue<"browserScrollDown"> };
    "step:browserScrollUp": import("./index.js").CascadeStep & { type: "browserScrollUp", value: StepValue<"browserScrollUp"> };
    "step:browserSelectOption": import("./index.js").CascadeStep & { type: "browserSelectOption", value: StepValue<"browserSelectOption"> };
    "step:browserSubagent": import("./index.js").CascadeStep & { type: "browserSubagent", value: StepValue<"browserSubagent"> };
    "step:buildCleaner": import("./index.js").CascadeStep & { type: "buildCleaner", value: StepValue<"buildCleaner"> };
    "step:captureBrowserConsoleLogs": import("./index.js").CascadeStep & { type: "captureBrowserConsoleLogs", value: StepValue<"captureBrowserConsoleLogs"> };
    "step:captureBrowserScreenshot": import("./index.js").CascadeStep & { type: "captureBrowserScreenshot", value: StepValue<"captureBrowserScreenshot"> };
    "step:checkDeployStatus": import("./index.js").CascadeStep & { type: "checkDeployStatus", value: StepValue<"checkDeployStatus"> };
    "step:checkpoint": import("./index.js").CascadeStep & { type: "checkpoint", value: StepValue<"checkpoint"> };
    "step:clickBrowserPixel": import("./index.js").CascadeStep & { type: "clickBrowserPixel", value: StepValue<"clickBrowserPixel"> };
    "step:clipboard": import("./index.js").CascadeStep & { type: "clipboard", value: StepValue<"clipboard"> };
    "step:cloudsqlExecuteSql": import("./index.js").CascadeStep & { type: "cloudsqlExecuteSql", value: StepValue<"cloudsqlExecuteSql"> };
    "step:cloudsqlUpdateSchema": import("./index.js").CascadeStep & { type: "cloudsqlUpdateSchema", value: StepValue<"cloudsqlUpdateSchema"> };
    "step:codeAcknowledgement": import("./index.js").CascadeStep & { type: "codeAcknowledgement", value: StepValue<"codeAcknowledgement"> };
    "step:codeAction": import("./index.js").CascadeStep & { type: "codeAction", value: StepValue<"codeAction"> };
    "step:codeSearch": import("./index.js").CascadeStep & { type: "codeSearch", value: StepValue<"codeSearch"> };
    "step:commandStatus": import("./index.js").CascadeStep & { type: "commandStatus", value: StepValue<"commandStatus"> };
    "step:compile": import("./index.js").CascadeStep & { type: "compile", value: StepValue<"compile"> };
    "step:compileApplet": import("./index.js").CascadeStep & { type: "compileApplet", value: StepValue<"compileApplet"> };
    "step:conversationHistory": import("./index.js").CascadeStep & { type: "conversationHistory", value: StepValue<"conversationHistory"> };
    "step:critique": import("./index.js").CascadeStep & { type: "critique", value: StepValue<"critique"> };
    "step:deleteDirectory": import("./index.js").CascadeStep & { type: "deleteDirectory", value: StepValue<"deleteDirectory"> };
    "step:deployFirebase": import("./index.js").CascadeStep & { type: "deployFirebase", value: StepValue<"deployFirebase"> };
    "step:dummy": import("./index.js").CascadeStep & { type: "dummy", value: StepValue<"dummy"> };
    "step:editNotebook": import("./index.js").CascadeStep & { type: "editNotebook", value: StepValue<"editNotebook"> };
    "step:ephemeralMessage": import("./index.js").CascadeStep & { type: "ephemeralMessage", value: StepValue<"ephemeralMessage"> };
    "step:errorMessage": import("./index.js").CascadeStep & { type: "errorMessage", value: StepValue<"errorMessage"> };
    "step:executeBrowserJavascript": import("./index.js").CascadeStep & { type: "executeBrowserJavascript", value: StepValue<"executeBrowserJavascript"> };
    "step:executeNotebook": import("./index.js").CascadeStep & { type: "executeNotebook", value: StepValue<"executeNotebook"> };
    "step:fileBreakdown": import("./index.js").CascadeStep & { type: "fileBreakdown", value: StepValue<"fileBreakdown"> };
    "step:fileChange": import("./index.js").CascadeStep & { type: "fileChange", value: StepValue<"fileChange"> };
    "step:find": import("./index.js").CascadeStep & { type: "find", value: StepValue<"find"> };
    "step:findAllReferences": import("./index.js").CascadeStep & { type: "findAllReferences", value: StepValue<"findAllReferences"> };
    "step:findings": import("./index.js").CascadeStep & { type: "findings", value: StepValue<"findings"> };
    "step:finish": import("./index.js").CascadeStep & { type: "finish", value: StepValue<"finish"> };
    "step:generateImage": import("./index.js").CascadeStep & { type: "generateImage", value: StepValue<"generateImage"> };
    "step:generic": import("./index.js").CascadeStep & { type: "generic", value: StepValue<"generic"> };
    "step:gitCommit": import("./index.js").CascadeStep & { type: "gitCommit", value: StepValue<"gitCommit"> };
    "step:grepSearch": import("./index.js").CascadeStep & { type: "grepSearch", value: StepValue<"grepSearch"> };
    "step:installAppletDependencies": import("./index.js").CascadeStep & { type: "installAppletDependencies", value: StepValue<"installAppletDependencies"> };
    "step:installAppletPackage": import("./index.js").CascadeStep & { type: "installAppletPackage", value: StepValue<"installAppletPackage"> };
    "step:internalSearch": import("./index.js").CascadeStep & { type: "internalSearch", value: StepValue<"internalSearch"> };
    "step:invokeSubagent": import("./index.js").CascadeStep & { type: "invokeSubagent", value: StepValue<"invokeSubagent"> };
    "step:kiInsertion": import("./index.js").CascadeStep & { type: "kiInsertion", value: StepValue<"kiInsertion"> };
    "step:knowledgeArtifacts": import("./index.js").CascadeStep & { type: "knowledgeArtifacts", value: StepValue<"knowledgeArtifacts"> };
    "step:knowledgeGeneration": import("./index.js").CascadeStep & { type: "knowledgeGeneration", value: StepValue<"knowledgeGeneration"> };
    "step:lintApplet": import("./index.js").CascadeStep & { type: "lintApplet", value: StepValue<"lintApplet"> };
    "step:lintDiff": import("./index.js").CascadeStep & { type: "lintDiff", value: StepValue<"lintDiff"> };
    "step:listBrowserPages": import("./index.js").CascadeStep & { type: "listBrowserPages", value: StepValue<"listBrowserPages"> };
    "step:listDirectory": import("./index.js").CascadeStep & { type: "listDirectory", value: StepValue<"listDirectory"> };
    "step:listResources": import("./index.js").CascadeStep & { type: "listResources", value: StepValue<"listResources"> };
    "step:lookupKnowledgeBase": import("./index.js").CascadeStep & { type: "lookupKnowledgeBase", value: StepValue<"lookupKnowledgeBase"> };
    "step:managerFeedback": import("./index.js").CascadeStep & { type: "managerFeedback", value: StepValue<"managerFeedback"> };
    "step:mcpTool": import("./index.js").CascadeStep & { type: "mcpTool", value: StepValue<"mcpTool"> };
    "step:memory": import("./index.js").CascadeStep & { type: "memory", value: StepValue<"memory"> };
    "step:moma": import("./index.js").CascadeStep & { type: "moma", value: StepValue<"moma"> };
    "step:move": import("./index.js").CascadeStep & { type: "move", value: StepValue<"move"> };
    "step:mquery": import("./index.js").CascadeStep & { type: "mquery", value: StepValue<"mquery"> };
    "step:notifyUser": import("./index.js").CascadeStep & { type: "notifyUser", value: StepValue<"notifyUser"> };
    "step:openBrowserUrl": import("./index.js").CascadeStep & { type: "openBrowserUrl", value: StepValue<"openBrowserUrl"> };
    "step:planInput": import("./index.js").CascadeStep & { type: "planInput", value: StepValue<"planInput"> };
    "step:plannerResponse": import("./index.js").CascadeStep & { type: "plannerResponse", value: StepValue<"plannerResponse"> };
    "step:postPrReview": import("./index.js").CascadeStep & { type: "postPrReview", value: StepValue<"postPrReview"> };
    "step:proposalFeedback": import("./index.js").CascadeStep & { type: "proposalFeedback", value: StepValue<"proposalFeedback"> };
    "step:proposeCode": import("./index.js").CascadeStep & { type: "proposeCode", value: StepValue<"proposeCode"> };
    "step:readBrowserPage": import("./index.js").CascadeStep & { type: "readBrowserPage", value: StepValue<"readBrowserPage"> };
    "step:readNotebook": import("./index.js").CascadeStep & { type: "readNotebook", value: StepValue<"readNotebook"> };
    "step:readResource": import("./index.js").CascadeStep & { type: "readResource", value: StepValue<"readResource"> };
    "step:readTerminal": import("./index.js").CascadeStep & { type: "readTerminal", value: StepValue<"readTerminal"> };
    "step:readUrlContent": import("./index.js").CascadeStep & { type: "readUrlContent", value: StepValue<"readUrlContent"> };
    "step:restartDevServer": import("./index.js").CascadeStep & { type: "restartDevServer", value: StepValue<"restartDevServer"> };
    "step:retrieveContent": import("./index.js").CascadeStep & { type: "retrieveContent", value: StepValue<"retrieveContent"> };
    "step:retrieveMemory": import("./index.js").CascadeStep & { type: "retrieveMemory", value: StepValue<"retrieveMemory"> };
    "step:rpcAction": import("./index.js").CascadeStep & { type: "rpcAction", value: StepValue<"rpcAction"> };
    "step:runCommand": import("./index.js").CascadeStep & { type: "runCommand", value: StepValue<"runCommand"> };
    "step:runExtensionCode": import("./index.js").CascadeStep & { type: "runExtensionCode", value: StepValue<"runExtensionCode"> };
    "step:searchKnowledgeBase": import("./index.js").CascadeStep & { type: "searchKnowledgeBase", value: StepValue<"searchKnowledgeBase"> };
    "step:searchWeb": import("./index.js").CascadeStep & { type: "searchWeb", value: StepValue<"searchWeb"> };
    "step:sendCommandInput": import("./index.js").CascadeStep & { type: "sendCommandInput", value: StepValue<"sendCommandInput"> };
    "step:setUpCloudsql": import("./index.js").CascadeStep & { type: "setUpCloudsql", value: StepValue<"setUpCloudsql"> };
    "step:setUpFirebase": import("./index.js").CascadeStep & { type: "setUpFirebase", value: StepValue<"setUpFirebase"> };
    "step:shellExec": import("./index.js").CascadeStep & { type: "shellExec", value: StepValue<"shellExec"> };
    "step:suggestedResponses": import("./index.js").CascadeStep & { type: "suggestedResponses", value: StepValue<"suggestedResponses"> };
    "step:systemMessage": import("./index.js").CascadeStep & { type: "systemMessage", value: StepValue<"systemMessage"> };
    "step:taskBoundary": import("./index.js").CascadeStep & { type: "taskBoundary", value: StepValue<"taskBoundary"> };
    "step:toolCallChoice": import("./index.js").CascadeStep & { type: "toolCallChoice", value: StepValue<"toolCallChoice"> };
    "step:toolCallProposal": import("./index.js").CascadeStep & { type: "toolCallProposal", value: StepValue<"toolCallProposal"> };
    "step:trajectoryChoice": import("./index.js").CascadeStep & { type: "trajectoryChoice", value: StepValue<"trajectoryChoice"> };
    "step:trajectorySearch": import("./index.js").CascadeStep & { type: "trajectorySearch", value: StepValue<"trajectorySearch"> };
    "step:userInput": import("./index.js").CascadeStep & { type: "userInput", value: StepValue<"userInput"> };
    "step:viewCodeItem": import("./index.js").CascadeStep & { type: "viewCodeItem", value: StepValue<"viewCodeItem"> };
    "step:viewContentChunk": import("./index.js").CascadeStep & { type: "viewContentChunk", value: StepValue<"viewContentChunk"> };
    "step:viewFile": import("./index.js").CascadeStep & { type: "viewFile", value: StepValue<"viewFile"> };
    "step:viewFileOutline": import("./index.js").CascadeStep & { type: "viewFileOutline", value: StepValue<"viewFileOutline"> };
    "step:wait": import("./index.js").CascadeStep & { type: "wait", value: StepValue<"wait"> };
    "step:workspaceApi": import("./index.js").CascadeStep & { type: "workspaceApi", value: StepValue<"workspaceApi"> };
    "step:writeBlob": import("./index.js").CascadeStep & { type: "writeBlob", value: StepValue<"writeBlob"> };
    "step:writeToFile": import("./index.js").CascadeStep & { type: "writeToFile", value: StepValue<"writeToFile"> };
}
